#!/usr/bin/env python

import argparse
import json
import sys

import odil

import jsondiff

def main():
    parser = argparse.ArgumentParser(
        description="Print the differences between two DICOM data sets")
    parser.add_argument("a")
    parser.add_argument("b")
    parser.add_argument(
        "--exclude", "-x", action="append", 
        help="Exclude elements from comparison")
    arguments = parser.parse_args()
    
    a = json.load(open(arguments.a))
    b = json.load(open(arguments.b))
    
    differences = jsondiff.get_differences(a, b, arguments.exclude)
    
    for difference in differences:
        if len(difference) == 1:
            path = difference[0]
            message = "deleted"
        else:
            path, new_value = difference
            message = str(new_value)
        
        print "{}: {}".format("/".join(str(x) for x in path), message)

    return 0 if (len(differences) == 0) else 1

if __name__ == "__main__":
    sys.exit(main())
