#!/usr/bin/env python

import argparse
import json
import sys

import jsondiff

def main():
    parser = argparse.ArgumentParser(
        description="Print the differences between two DICOM data sets")
    parser.add_argument("a")
    parser.add_argument("b")
    parser.add_argument(
        "--exclude", "-x", action="append", 
        help="Exclude elements from comparison")
    arguments = parser.parse_args()
    
    a = json.load(open(arguments.a))
    b = json.load(open(arguments.b))
    
    differences = jsondiff.get_differences(a, b, arguments.exclude)
    
    for difference in differences:
        path = [str(x) for x in difference[0]]
        reason = difference[1]
        details = difference[2:]
        print(
            "{}: {}, {}".format(
                "/".join(path), 
                reason, " ".join(str(x) for x in details)))

    return 0 if (len(differences) == 0) else 1

if __name__ == "__main__":
    sys.exit(main())
